baseURL = 'https://example.org'
languageCode = 'en-us'
title = 'Ideas'
theme = 'PaperMod'

[params]
  env = "production"
  title = "Ideas"
  description = "I have ideas.."
  keywords = ["ideas"]
  author = "Your Name"
  
  defaultTheme = "auto"
  disableThemeToggle = false
  
  ShowReadingTime = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
  ShowWordCount = false
  ShowRssButtonInSectionTermList = false
  
  homeInfoParams.Title = ""
  homeInfoParams.Content = "I have ideas.."


[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github"
